services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8181:81'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  frps:
    image: snowdreamtech/frps
    container_name: frps
    restart: always
    ports:
      - "7000:7000"
      - "7500:7500"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./frps.ini:/etc/frp/frps.ini
